######################################################################
# Automatically generated by qmake (2.01a) mar. mars 6 13:35:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h QSchedule.h QTimeSlot.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp QSchedule.cpp QTimeSlot.cpp
