######################################################################
# Automatically generated by qmake (2.01a) lun. mars 5 21:32:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h QSchedule.h QTimeSlot.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp QSchedule.cpp QTimeSlot.cpp
